version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
   interval: "weekly"
  labels:
    - "dependencies"
    - "ok-to-test"
  open-pull-requests-limit: 20
  groups:
    kubernetes:
      patterns:
        - "k8s.io/*"
        - "sigs.k8s.io/*"
