version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - loggercheck
    - mirror
    - misspell
    - nilnil
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: composites
      - path: (.+)\.go$
        text: 'ST1001: should not use dot imports'
    paths:
      - third_party$
      - builtin$
      - examples$
      - pkg/common/concurrentviper/generated\.go$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
