# golangci-lint configuration file.
# Read more at: https://github.com/golangci/golangci-lint#config-file

run:
  deadline: 30m
  issues-exit-code: 1
  tests: true
linters:
  disable-all: true
  enable:
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - unused
    - gofumpt
issues:
  exclude:
    - composites
