apiVersion: v1
kind: Pod
metadata:
  generateName: anyuid-pod
spec:
  containers:
    - name: hello
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080
  securityContext:
    runAsNonRoot: true
    runAsUser: 987654321
