package providers

// DO NOT EDIT THIS FILE. It is generated by the Makefile.
// This import list is necessary due to the statically linked nature of go
import (
	_ "github.com/openshift/osde2e/pkg/common/providers/crc"
	_ "github.com/openshift/osde2e/pkg/common/providers/mock"
	_ "github.com/openshift/osde2e/pkg/common/providers/ocmprovider"
	_ "github.com/openshift/osde2e/pkg/common/providers/rosaprovider"
)
