tests:
  testsToRun:
  - '\[Suite\: service-definition\]'
  - 'Managed Cluster Validating Webhooks'
  testHarnesses:
    - quay.io/app-sre/aws-vpce-operator-test-harness
    - quay.io/app-sre/splunk-forwarder-operator-test-harness
    - quay.io/app-sre/ocm-agent-operator-test-harness
    - quay.io/app-sre/osd-metrics-exporter-test-harness
    - quay.io/app-sre/custom-domains-operator-test-harness
    - quay.io/app-sre/managed-node-metadata-operator-test-harness
    - quay.io/app-sre/rbac-permissions-operator-test-harness
  suiteTimeout: 900
