apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: osde2e-focused-tests

parameters:
  - name: HARNESS_IMAGE_TAG
    required: true
  - name: OSDE2E_CONFIGS
    required: true
  - name: TEST_HARNESS_IMAGE
    required: true
  - name: OCM_TOKEN
    required: true
  - name: AWS_ACCESS_KEY_ID
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    required: true
  - name: AWS_REGION
    required: true
  - name: JOBID
    generate: expression
    from: "[0-9a-z]{7}"
  - name: IMAGE_TAG
    value: ''
    required: true
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: osde2e-focused-test-job-${IMAGE_TAG}-${JOBID}
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: osde2e
              image: quay.io/app-sre/osde2e:latest
              command:
                - /osde2e
              args:
                - test
                - --configs
                - ${OSDE2E_CONFIGS}
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                seccompProfile:
                  type: RuntimeDefault
              env:
                - name: TEST_HARNESSES
                  value: ${TEST_HARNESS_IMAGE}:${HARNESS_IMAGE_TAG}
                - name: OCM_TOKEN
                  value: ${OCM_TOKEN}
                - name: AWS_ACCESS_KEY_ID
                  value: ${AWS_ACCESS_KEY_ID}
                - name: AWS_SECRET_ACCESS_KEY
                  value: ${AWS_SECRET_ACCESS_KEY}
                - name: AWS_REGION
                  value: ${AWS_REGION}