#!/bin/bash
#
# This will generate a golang file that imports the various reporters so that they're included in the build of osde2e.
# This is a bit kludgy, but it'll allow us to drop in a new reporter and have it built in automatically.
#

REPORTERS_DIR="$(dirname "$0")/../pkg/reporting/reporters"

echo "package reporters"
echo ""
echo "// DO NOT EDIT THIS FILE. It is generated by the Makefile."
echo "// This import list is necessary due to the statically linked nature of go"
echo "import ("
find "$REPORTERS_DIR" -mindepth 1 -type d -print0 | sort -z | while read -r -d $'\0' reporter; do
REPORTER_NAME="$(basename "$reporter")"
echo -e "\t_ \"github.com/openshift/osde2e/pkg/reporting/reporters/$REPORTER_NAME\""
done
echo ")"
