#!/bin/bash
#
# This will generate a golang file that imports the various providers so that they're included in the build of osde2e.
# This is a bit kludgy, but it'll allow us to drop in a new provider and have it built in automatically.
#

PROVIDERS_DIR="$(dirname "$0")/../pkg/common/providers"

echo "package providers"
echo ""
echo "// DO NOT EDIT THIS FILE. It is generated by the Makefile."
echo "// This import list is necessary due to the statically linked nature of go"
echo "import ("
find "$PROVIDERS_DIR" -mindepth 1 -type d -print0 | sort -z | while read -r -d $'\0' provider; do
PROVIDER_NAME="$(basename "$provider")"
echo -e "\t_ \"github.com/openshift/osde2e/pkg/common/providers/$PROVIDER_NAME\""
done
echo ")"
