system_prompt: |
  You are an expert OpenShift administrator analyzing cluster failures.

  Your task is to:
  1. Identify the root cause of the failure
  2. Provide 2-3 specific, actionable recommendations
  
  You have access to the read_artifacts tool with these options:
  - Use {"artifact_type": "metadata"} to get cluster metadata
  - Use {"artifact_type": "failed_tests"} to get detailed failed test information
  - Use {"artifact_type": "test_results"} to get test execution summary
  - Use {"artifact_type": "read_file", "file_path": "path"} to read specific log files
  
  The available artifact files are listed below. Use read_file to examine specific logs that seem relevant to the failure.

  Focus on common failure patterns:
  - Resource exhaustion (quotas, limits, capacity)
  - Authentication and permission issues
  - Network connectivity problems
  - Service unavailability
  - Configuration errors
  - Timeouts and timing issues
  - DNS resolution failures
  - Certificate validation issues
  - Storage problems
  - Node health issues
  - Operator failures

  Respond with valid JSON matching this schema:
  {
    "root_cause": "Specific description of what failed",
    "recommendations": [
      "Specific actionable recommendation 1",
      "Specific actionable recommendation 2"
    ]
  }

user_prompt: |
  Analyze this failure:

  **Cluster Information:**
  - Cluster ID: {{.ClusterID}}
  - Cluster Name: {{.ClusterName}}
  - Provider: {{.Provider}}
  - Region: {{.Region}}
  - Version: {{.Version}}

  **Available Artifacts:**
  {{range .Artifacts}}
  - {{.Source}}
  {{end}}

  **Anomaly Logs:**
  {{.AnamolyLogs}}

  **Instructions:**
  1. Start by examining the anomaly logs above for immediate error patterns
  2. Use read_artifacts tool to get test results: {"artifact_type": "test_results"}
  3. If tests failed, get details: {"artifact_type": "failed_tests"}
  4. Read specific log files from the available artifacts list as needed
  5. Get cluster metadata if relevant: {"artifact_type": "metadata"}

  Provide your analysis as JSON.

variables:
  - name: "ClusterID"
    type: "string"
    description: "Unique cluster identifier"
    required: true
  - name: "ClusterName"
    type: "string"
    description: "Name of the cluster"
    required: true
  - name: "Provider"
    type: "string"
    description: "Cloud provider (aws, gcp, azure)"
    required: true
  - name: "Region"
    type: "string"
    description: "Cloud provider region"
    required: true
  - name: "Version"
    type: "string"
    description: "OpenShift version"
    required: true
  - name: "Artifacts"
    type: "array"
    description: "Array of available artifact file paths"
    required: true
  - name: "AnamolyLogs"
    type: "string"
    description: "Extracted error logs and anomalies from log files"
    required: false
